services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mnesis:latest
        env_file:
            - ./packages/server/.env
        ports:
            - "80:3000"
