services:
    server:
        build:
            context: ./packages/server
            dockerfile: Dockerfile
        image: mnesis-server:latest
        env_file:
            - ./packages/server/.env
        ports:
            - "3000:3000"
        restart: unless-stopped

    app:
        build:
            context: ./packages/app/
            dockerfile: Dockerfile
        image: mnesis-app:latest
        env_file:
            - ./packages/app/.env
        ports:
            - "80:80"
        volumes:
            - ./packages/app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - server
